### ISSUE TITLE
Failed compiling using ESP-IDF framework

### ISSUE THREAD

**Issue by yanivf38** [Rihan9/LD2412#10] opened 2024-10-24 22:48 UTC
Hi Rihan,

Can you add to the switch statement in set_mode an else case that will return. I get an error that CMD isn't initialized.

**Comment by Rihan9** [comment] 2024-10-25 07:02
Hi @yanivf38, I'm pretty sure this is a duplicate of #8 , I'm closing this

**Closed as completed by Rihan9** 2024-10-25 07:02 UTC
